project:
  type: website
  output-dir: docs

website:
  title: CloudBrain
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Methods"
        file: Methods_Development.qmd
      - text: "Analysis"
        file: Data_Analysis.qmd
      - text: "Visualization"
        file: Visualization.qmd

  sidebar:
    - title: "Methods"
      style: "docked"
      background: light
      contents:
        - Methods_Development.qmd
        - Method 1.qmd
        - Method 2.qmd

    - title: "Analysis"
      contents:
        - Data_Analysis.qmd
        - Experimental Design Making.qmd
        - ANOVA
        # navigation items

    - title: "Visualization"
      contents:
        - Visualization.qmd
        - Soil Profile Sketch.qmd
        - Soil Textural Cluster.qmd
        # navigation items

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

