project:
  type: website
  output-dir: docs

website:
  title: Knowledge Garden
  navbar:
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Notes"
        file: Notes.qmd
      - text: "Methods"
        file: Methods_Development.qmd
      - text: "Analysis"
        file: Data_Analysis.qmd
      - text: "Visualization"
        file: Visualization.qmd
  page-navigation: TRUE
  page-footer: "Copyright 2023, LJD Villasica"
  
  sidebar:
    - title: "Notes"
      style: "docked"
      background: light
      contents:
        - Notes.qmd
        - Note 1
        - Note 2
        
    - title: "Methods"
      style: "docked"
      background: light
      contents:
        - Methods_Development.qmd
        - Method 1
        - Method 2

    - title: "Analysis"
      contents:
        - Data_Analysis.qmd
        - Experimental Design Making
        - ANOVA
        # navigation items

    - title: "Visualization"
      contents:
        - Visualization.qmd
        - Soil Profile Sketch
        - Soil Textural Cluster.qmd
        # navigation items

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

license: "CC BY-NC-ND"
